# Generated by Django 4.0.4 on 2022-04-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createAt', models.TimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=500)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['createAt'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('published', models.BooleanField(default=True)),
                ('createAt', models.TimeField(auto_now_add=True)),
                ('updateAt', models.TimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=1000)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['createAt'],
            },
        ),
    ]
