# Generated by Django 4.0.4 on 2022-05-24 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='authorId',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='authorId',
            new_name='author',
        ),
    ]
